### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#609]
## Major Upgrade
- [ ] Update psycopg2
- [ ] Update APISpec
- [ ] Update redoc template for API documentation https://github.com/Redocly/redoc
- [ ] Update alembic and Flask-Migrate
- [ ] Rest of the libraries all have to be updated together

## Remove stuff
- [ ] Remove data_generator or update it so that it is usable. It currently references modules that no longer exist
- [ ] Remove DELETE operation for study endpoint. Dataservice locks up anyway due to #346 
- [ ] Remove dead parts of model - `CavaticaApp, StudyFile, Task, TaskGenomicFile`

## Fix stuff
- [x] Update local dev instructions. Use .env_local.sh with exports
- [ ] Remove ERD generation or update it so that it correctly illustrated relations (not reversed)

## New stuff
- Consider moving to Pipfile to manage dependencies https://github.com/pypa/pipfile
- Upgrade to newer version of Python 3.9 or 3.11. Some libraries are starting to end support of 3.7 which is what we use
- Tighten up code style - use black formatter

**Comment by znatty22** [comment]
Closing. This work is being aborted and wrapped up since we’ve had a change in strategy. It turned out that the upgrade would require so many breaking changes to be fixed that it would take a long time to implement and would be very difficult to regression test.
